name: cd-on-deploy

on:
    deployment: #se ejecuta cunaod se crea un deployment

jobs:
    alerts:
        runs-on: ubuntu-latest
        steps:
            - run: echo "sending slack alert to get deploy approved"
            - run: echo "${{toJson(github.event)}}"