name: upper-image
on:
    push:
        paths:
            - ".github/workflows/upper-image.yml"
            - "upper/**"
    workflow_dispatch:


permissions:
    packages: write
    contents: read #no es necesario en repos publicos
jobs:
    image:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: docker version
            - run: docker image build -t upper .
              working-directory: ./upper
            - name: test it
              run: docker container run upper hello wes
            - uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{github.repository_owner}}
                password: ${{secrets.GITHUB_TOKEN}}
            - run: docker tag upper ghrc.io/username/upper:latest
            - run: docker tag upper ghrc.io/username/upper:${{github.ref_name}}
            - run: docker push upper ghrc.io/username/upper:latest
            - run: docker push upper ghrc.io/username/upper:${{github.ref_name}}


